<?php

$routes = [	'home' => 'HomeController',
			'login_form' => 'AuthController',
			'login' => 'AuthController',
			'register_form' => 'AuthController',
			'register' => 'AuthController',
			'forgotten_password' => 'AuthController',
			'logout' => 'AuthController',
			'chat_home' => 'ChatController',
			'create_channel' => 'ChatController',
			'create_groupe' => 'ChatController',
			'friends_list' => 'ChatController',
			'send_friend_request' => 'ChatController',
			'accept_friend_request' => 'ChatController',
			'decline_friend_request' => 'ChatController',
			'cancel_friend_request' => 'ChatController',
			'delete_friend' => 'ChatController',
			'open_conversation' => 'ChatController',
			'save_message' => 'ChatController',
			'parameters' => 'SettingsController'];
